version: '3'

services:
  mongodb:
    env_file:
      - .env
    image: mongo:3.2
    container_name: mongodb
  node:
    env_file:
      - .env
    build: .
    container_name: node
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - mongodb
